- name: run stress
  script: files/stress.sh
- name: kill fio
  command: killall fio
  ignore_errors: True
- name: run fio
  command: fio -direct=1 -ioengine=libaio -rw=write -bs=1m -iodepth=16 -numjobs=16 -runtime=1d -time_based -filename=/mnt/fio -size=100g -rate=1g -name=run_test
  async: 5
  poll: 0
