- name: create raid
  script: files/create_raid.sh
- name: create filesystem on /dev/sdb1
  filesystem: fstype=ext4 dev=/dev/sdb1
- name: mount /dev/sdb1
  mount: name=/mnt fstype=ext4 src=/dev/sdb1 state=mounted
